version: 2
updates:
  - package-ecosystem: npm
    directory: /sdk/typescript
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
